### ISSUE TITLE
Question about "ca" in point cloud

### ISSUE THREAD

**Issue by Winner-Nick** [IGLICT/GaussianMesh#1]
Hello! Thank you for developing GaussianMesh; it’s an impressive piece of work! While trying to train the model, I encountered some questions and hope to receive some guidance.

1. Could you clarify what is meant by using instant-nsr-pl to generate the mesh? Is it possible to generate the mesh without providing an explicit mesh input, using only images and the initial results from COLMAP as input?

2. I used the point cloud result from the original Gaussian training, along with images and sparse/transform.json as input, and ran the following command:
`python train_bg_gaussian.py -r 1 -s <path to COLMAP dataset> -m <output_path> --mesh_gaussian_path <output_path>/point_cloud/iteration_30000/point_cloud.ply --is_exist_bg`
However, I received the following error:
`ValueError: no field of name ca`
Could you explain what “ca” refers to in the point cloud file, and why it might be missing from the original Gaussian training results?

I suspect there may be a gap in my understanding of the project. My expectation is that, by inputting my images, camera poses, initial point cloud, and the results of the original Gaussian training, the model could directly generate the mesh. I would appreciate any insights the authors can provide.

Thank you again for your contributions to this field!

**Comment by tommaoer** [comment]
Thank you for your questions.

1. Our approach is designed to support deformation, which requires high-quality meshes. The instant-nsr-pl can reconstruct mesh more quickly and effectively. Our method is based on the vanilla 3DGS, which is challenging to extract mesh  by using only multi-view images and colmap camera. Or other reconstruction method is OK (like 2DGS or GOF).

2. The PLY file format stored by mesh_gaussian_path is different from the original Gaussian storage format. Please refer to the `save_ply` and `load_ply` functions in `scene/mesh_based_gaussian_model.py` for details.  
- "ca,cb,cc" refers to barycentric coordinates of gaussians on  certain triangles "fid"
